version: '0.2'
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
    - n 16
  pre_build:
    commands:
    - cd application
    - yarn
  build:
    commands:
    - yarn run build
    - aws s3 sync build/. s3://$BUCKET_NAME --delete
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths
      "/*"
